import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Sidebar from "./_components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  header
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-full flex gap-2">
            <Sidebar />
            {children}
        </main>
      </body>
    </html>
  );
}
